services:
  server:
    build: api
    ports:
      - 3000:3000
    environment:
      SECRET_TOKEN: ${SECRET_TOKEN}
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@localhost:5432/${DB_NAME}?schema=public
  database:
    image: docker.io/library/postgres:alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
