# @import auth.http
# @import polls.http

###
# @ref poll
# @name pollitem
POST /pollitem/create
Content-Type: application/json

{
    "pollId": "{{poll.poll_id}}",
    "description": "IKARIAM"
}

###
# @ref pollitem
GET /pollitem/{{pollitem.id}}
Content-Type: application/json

###
# @ref pollitem
DELETE /pollitem/{{pollitem.id}}/delete
Content-Type: application/json

###
# @ref pollitem
PATCH /pollitem/{{pollitem.id}}/update
Content-Type: application/json

{
    "pollId": "{{poll.poll_id}}",
    "description": "Star guardian Lulu"
}