# @import auth.http
# @import polls.http

###
# @ref poll
# @name pollitem
POST /pollitem/create
Content-Type: application/json

{
    "pollId": "{{poll.poll_id}}",
    "description": "star guardian ahri123"
}

###
# @ref pollitem
GET /pollitem/{{pollitem.id}}
Content-Type: application/json
