# @import auth.http

###
# @ref profile
POST /poll/create
Content-Type: application/json

{
    "userId": "{{ profile.id }}",
    "title": "testii",
    "description": "testii",
    "expires": "2024-02-25T17:53:57.494Z",
    "multipleAnswers": false,
    "private": false
}
