from node:alpine

# Install necessities
run apk upgrade
run apk add python3 py3-pip

# Copy files
workdir api
copy . .
run pip install -r requirements.txt --break-system-packages

# Generate client
run prisma generate

# Run server
entrypoint ["waitress-serve", "app:app"]
