name: Code Maintenance

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  detect-secrets:
    name: No committed secrets
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          set-safe-directory: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install detect-secrets
        run: pip install detect-secrets
      - name: Scan for secrets
        run: detect-secrets scan --baseline .secrets.baseline
  prettier-check:
    name: Prettier formatted files
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          set-safe-directory: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install prettier
        run: npm install -g prettier
      - name: Run prettier against files
        run: prettier -c .
  analyze-code:
    name: No code smells
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/setup-env
      - name: Lint code
        run: npm run lint
  run-tests:
    name: Tests pass
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/setup-env
      - name: Run unit tests
        run: npm run test
